package com.gigware.goldmine;

import java.util.Arrays;
import java.util.List;

enum EnumGroup {
    ADSENSE(Arrays.asList(
    ), Arrays.asList(
            EnumMetrics.ADSENSE__ADSENSE_AD_UNITS_VIEWED,
            EnumMetrics.ADSENSE__ADSENSE_REVENUE,
            EnumMetrics.ADSENSE__ADSENSE_ADS_CLICKED,
            EnumMetrics.ADSENSE__ADSENSE_COVERAGE,
            EnumMetrics.ADSENSE__ADSENSE_PAGE_IMPRESSIONS,
            EnumMetrics.ADSENSE__ADSENSE_VIEWABLE_IMPRESSION_PERCENT,
            EnumMetrics.ADSENSE__ADSENSE_IMPRESSIONS,
            EnumMetrics.ADSENSE__ADSENSE_CTR,
            EnumMetrics.ADSENSE__ADSENSE_ECPM,
            EnumMetrics.ADSENSE__ADSENSE_EXITS
    )),
    ADWORDS(Arrays.asList(
            EnumDimensions.ADWORDS__TRUEVIEW_VIDEO_AD,
            EnumDimensions.ADWORDS__GOOGLE_ADS_AD_GROUP_ID,
            EnumDimensions.ADWORDS__AD_DISTRIBUTION_NETWORK,
            EnumDimensions.ADWORDS__DESTINATION_URL,
            EnumDimensions.ADWORDS__PLACEMENT_TYPE,
            EnumDimensions.ADWORDS__PLACEMENT_DOMAIN,
            EnumDimensions.ADWORDS__GOOGLE_ADS_CAMPAIGN_ID,
            EnumDimensions.ADWORDS__DISPLAY_URL,
            EnumDimensions.ADWORDS__QUERY_WORD_COUNT,
            EnumDimensions.ADWORDS__GOOGLE_ADS_CREATIVE_ID,
            EnumDimensions.ADWORDS__AD_FORMAT,
            EnumDimensions.ADWORDS__QUERY_MATCH_TYPE,
            EnumDimensions.ADWORDS__GOOGLE_ADS_CUSTOMER_ID,
            EnumDimensions.ADWORDS__KEYWORD_MATCH_TYPE,
            EnumDimensions.ADWORDS__GOOGLE_ADS_CRITERIA_ID,
            EnumDimensions.ADWORDS__GOOGLE_ADS_AD_GROUP,
            EnumDimensions.ADWORDS__GOOGLE_ADS_AD_SLOT,
            EnumDimensions.ADWORDS__TARGETING_TYPE,
            EnumDimensions.ADWORDS__PLACEMENT_URL,
            EnumDimensions.ADWORDS__SEARCH_QUERY
    ), Arrays.asList(
            EnumMetrics.ADWORDS__CPM,
            EnumMetrics.ADWORDS__CPC,
            EnumMetrics.ADWORDS__RPC,
            EnumMetrics.ADWORDS__ROAS,
            EnumMetrics.ADWORDS__COST_PER_TRANSACTION,
            EnumMetrics.ADWORDS__CTR,
            EnumMetrics.ADWORDS__IMPRESSIONS,
            EnumMetrics.ADWORDS__CLICKS,
            EnumMetrics.ADWORDS__COST_PER_GOAL_CONVERSION,
            EnumMetrics.ADWORDS__COST_PER_CONVERSION,
            EnumMetrics.ADWORDS__COST
    )),
    AD_EXCHANGE(Arrays.asList(
    ), Arrays.asList(
            EnumMetrics.AD_EXCHANGE__ADX_CLICKS,
            EnumMetrics.AD_EXCHANGE__ADX_REVENUE_PER_1000_SESSIONS,
            EnumMetrics.AD_EXCHANGE__ADX_MONETIZED_PAGEVIEWS,
            EnumMetrics.AD_EXCHANGE__ADX_REVENUE,
            EnumMetrics.AD_EXCHANGE__ADX_COVERAGE,
            EnumMetrics.AD_EXCHANGE__ADX_IMPRESSIONS,
            EnumMetrics.AD_EXCHANGE__ADX_IMPRESSIONS_PER_SESSION,
            EnumMetrics.AD_EXCHANGE__ADX_ECPM,
            EnumMetrics.AD_EXCHANGE__ADX_VIEWABLE_IMPRESSIONS_PERCENT,
            EnumMetrics.AD_EXCHANGE__ADX_CTR
    )),
    APP_TRACKING(Arrays.asList(
            EnumDimensions.APP_TRACKING__APP_NAME,
            EnumDimensions.APP_TRACKING__SCREEN_NAME,
            EnumDimensions.APP_TRACKING__APP_ID,
            EnumDimensions.APP_TRACKING__LANDING_SCREEN,
            EnumDimensions.APP_TRACKING__SCREEN_DEPTH,
            EnumDimensions.APP_TRACKING__EXIT_SCREEN,
            EnumDimensions.APP_TRACKING__APP_INSTALLER_ID,
            EnumDimensions.APP_TRACKING__APP_VERSION
    ), Arrays.asList(
            EnumMetrics.APP_TRACKING__SCREEN_VIEWS,
            EnumMetrics.APP_TRACKING__SCREENS_PER_SESSION,
            EnumMetrics.APP_TRACKING__TIME_ON_SCREEN,
            EnumMetrics.APP_TRACKING__UNIQUE_SCREEN_VIEWS,
            EnumMetrics.APP_TRACKING__AVG_TIME_ON_SCREEN
    )),
    AUDIENCE(Arrays.asList(
            EnumDimensions.AUDIENCE__AGE,
            EnumDimensions.AUDIENCE__AFFINITY_CATEGORY_REACH,
            EnumDimensions.AUDIENCE__INMARKET_SEGMENT,
            EnumDimensions.AUDIENCE__GENDER,
            EnumDimensions.AUDIENCE__OTHER_CATEGORY
    ), Arrays.asList(
    )),
    CHANNEL_GROUPING(Arrays.asList(
            EnumDimensions.CHANNEL_GROUPING__DEFAULT_CHANNEL_GROUPING
    ), Arrays.asList(
    )),
    CONTENT_EXPERIMENTS(Arrays.asList(
            EnumDimensions.CONTENT_EXPERIMENTS__EXPERIMENT_NAME,
            EnumDimensions.CONTENT_EXPERIMENTS__EXPERIMENT_ID_WITH_VARIANT,
            EnumDimensions.CONTENT_EXPERIMENTS__EXPERIMENT_ID,
            EnumDimensions.CONTENT_EXPERIMENTS__VARIANT
    ), Arrays.asList(
    )),
    CONTENT_GROUPING(Arrays.asList(
            EnumDimensions.CONTENT_GROUPING__PAGE_GROUP_XX,
            EnumDimensions.CONTENT_GROUPING__PREVIOUS_PAGE_GROUP_XX,
            EnumDimensions.CONTENT_GROUPING__LANDING_PAGE_GROUP_XX
    ), Arrays.asList(
            EnumMetrics.CONTENT_GROUPING__UNIQUE_VIEWS_XX
    )),
    CUSTOM_VARIABLES_OR_COLUMNS(Arrays.asList(
            EnumDimensions.CUSTOM_VARIABLES_OR_COLUMNS__CUSTOM_DIMENSION_XX,
            EnumDimensions.CUSTOM_VARIABLES_OR_COLUMNS__CUSTOM_VARIABLE_VALUE_XX,
            EnumDimensions.CUSTOM_VARIABLES_OR_COLUMNS__CUSTOM_VARIABLE_KEY_XX
    ), Arrays.asList(
            EnumMetrics.CUSTOM_VARIABLES_OR_COLUMNS__CALCULATED_METRIC,
            EnumMetrics.CUSTOM_VARIABLES_OR_COLUMNS__CUSTOM_METRIC_XX_VALUE
    )),
    DOUBLECLICK_BID_MANAGER(Arrays.asList(
            EnumDimensions.DOUBLECLICK_BID_MANAGER__DV360_SITE_CM360_MODEL,
            EnumDimensions.DOUBLECLICK_BID_MANAGER__DV360_LINE_ITEM_ID_GA_MODEL,
            EnumDimensions.DOUBLECLICK_BID_MANAGER__DV360_LINE_ITEM_ID_CM360_MODEL,
            EnumDimensions.DOUBLECLICK_BID_MANAGER__DV360_LINE_ITEM_NAME_GA_MODEL,
            EnumDimensions.DOUBLECLICK_BID_MANAGER__DV360_INSERTION_ORDER_CM360_MODEL,
            EnumDimensions.DOUBLECLICK_BID_MANAGER__DV360_ADVERTISER_GA_MODEL,
            EnumDimensions.DOUBLECLICK_BID_MANAGER__DV360_ADVERTISER_ID_CM360_MODEL,
            EnumDimensions.DOUBLECLICK_BID_MANAGER__DV360_ADVERTISER_CM360_MODEL,
            EnumDimensions.DOUBLECLICK_BID_MANAGER__DV360_INSERTION_ORDER_GA_MODEL,
            EnumDimensions.DOUBLECLICK_BID_MANAGER__DV360_CREATIVE_ID_CM360_MODEL,
            EnumDimensions.DOUBLECLICK_BID_MANAGER__DV360_EXCHANGE_ID_CM360_MODEL,
            EnumDimensions.DOUBLECLICK_BID_MANAGER__DV360_LINE_ITEM_CM360_MODEL,
            EnumDimensions.DOUBLECLICK_BID_MANAGER__DV360_SITE_GA_MODEL,
            EnumDimensions.DOUBLECLICK_BID_MANAGER__DV360_INSERTION_ORDER_ID_CM360_MODEL,
            EnumDimensions.DOUBLECLICK_BID_MANAGER__DV360_CREATIVE_ID_GA_MODEL,
            EnumDimensions.DOUBLECLICK_BID_MANAGER__DV360_ADVERTISER_ID_GA_MODEL,
            EnumDimensions.DOUBLECLICK_BID_MANAGER__DV360_SITE_ID_CM360_MODEL,
            EnumDimensions.DOUBLECLICK_BID_MANAGER__DV360_INSERTION_ORDER_ID_GA_MODEL,
            EnumDimensions.DOUBLECLICK_BID_MANAGER__DV360_EXCHANGE_ID_GA_MODEL,
            EnumDimensions.DOUBLECLICK_BID_MANAGER__DV360_EXCHANGE_CM360_MODEL,
            EnumDimensions.DOUBLECLICK_BID_MANAGER__DV360_EXCHANGE_GA_MODEL,
            EnumDimensions.DOUBLECLICK_BID_MANAGER__DV360_SITE_ID_GA_MODEL
    ), Arrays.asList(
            EnumMetrics.DOUBLECLICK_BID_MANAGER__DV360_IMPRESSIONS,
            EnumMetrics.DOUBLECLICK_BID_MANAGER__DV360_ROAS,
            EnumMetrics.DOUBLECLICK_BID_MANAGER__DV360_ECPM,
            EnumMetrics.DOUBLECLICK_BID_MANAGER__DV360_CONVERSIONS,
            EnumMetrics.DOUBLECLICK_BID_MANAGER__DV360_CTR,
            EnumMetrics.DOUBLECLICK_BID_MANAGER__DV360_COST,
            EnumMetrics.DOUBLECLICK_BID_MANAGER__DV360_CLICKS,
            EnumMetrics.DOUBLECLICK_BID_MANAGER__DV360_ECPC,
            EnumMetrics.DOUBLECLICK_BID_MANAGER__DV360_ECPA
    )),
    DOUBLECLICK_CAMPAIGN_MANAGER(Arrays.asList(
            EnumDimensions.DOUBLECLICK_CAMPAIGN_MANAGER__CM360_RENDERING_ID_CM360_MODEL,
            EnumDimensions.DOUBLECLICK_CAMPAIGN_MANAGER__CM360_CAMPAIGN_ID_CM360_MODEL,
            EnumDimensions.DOUBLECLICK_CAMPAIGN_MANAGER__CM360_AD_TYPE_ID_CM360_MODEL,
            EnumDimensions.DOUBLECLICK_CAMPAIGN_MANAGER__CM360_AD_TYPE_ID,
            EnumDimensions.DOUBLECLICK_CAMPAIGN_MANAGER__CM360_ACTIVITY_GROUP,
            EnumDimensions.DOUBLECLICK_CAMPAIGN_MANAGER__CM360_CREATIVE_VERSION_GA_MODEL,
            EnumDimensions.DOUBLECLICK_CAMPAIGN_MANAGER__CM360_CREATIVE_CM360_MODEL,
            EnumDimensions.DOUBLECLICK_CAMPAIGN_MANAGER__CM360_AD_TYPE_GA_MODEL,
            EnumDimensions.DOUBLECLICK_CAMPAIGN_MANAGER__CM360_ACTIVITY_ID,
            EnumDimensions.DOUBLECLICK_CAMPAIGN_MANAGER__CM360_ADVERTISER_CM360_MODEL,
            EnumDimensions.DOUBLECLICK_CAMPAIGN_MANAGER__CM360_ATTRIBUTION_TYPE_CM360_MODEL,
            EnumDimensions.DOUBLECLICK_CAMPAIGN_MANAGER__CM360_ACTIVITY_AND_GROUP,
            EnumDimensions.DOUBLECLICK_CAMPAIGN_MANAGER__CM360_AD_GA_MODEL,
            EnumDimensions.DOUBLECLICK_CAMPAIGN_MANAGER__CM360_CREATIVE_ID_CM360_MODEL,
            EnumDimensions.DOUBLECLICK_CAMPAIGN_MANAGER__CM360_RENDERING_ID_GA_MODEL,
            EnumDimensions.DOUBLECLICK_CAMPAIGN_MANAGER__CM360_SITE_GA_MODEL,
            EnumDimensions.DOUBLECLICK_CAMPAIGN_MANAGER__CM360_FLOODLIGHT_CONFIGURATION_ID,
            EnumDimensions.DOUBLECLICK_CAMPAIGN_MANAGER__CM360_AD_ID_GA_MODEL,
            EnumDimensions.DOUBLECLICK_CAMPAIGN_MANAGER__CM360_CREATIVE_ID_GA_MODEL,
            EnumDimensions.DOUBLECLICK_CAMPAIGN_MANAGER__CM360_FLOODLIGHT_CONFIGURATION_ID_CM360_MODEL,
            EnumDimensions.DOUBLECLICK_CAMPAIGN_MANAGER__CM360_AD_TYPE_CM360_MODEL,
            EnumDimensions.DOUBLECLICK_CAMPAIGN_MANAGER__CM360_CREATIVE_VERSION_CM360_MODEL,
            EnumDimensions.DOUBLECLICK_CAMPAIGN_MANAGER__CM360_ACTIVITY,
            EnumDimensions.DOUBLECLICK_CAMPAIGN_MANAGER__CM360_ADVERTISER_ID_GA_MODEL,
            EnumDimensions.DOUBLECLICK_CAMPAIGN_MANAGER__CM360_SITE_ID_GA_MODEL,
            EnumDimensions.DOUBLECLICK_CAMPAIGN_MANAGER__CM360_PLACEMENT_CM360_MODEL,
            EnumDimensions.DOUBLECLICK_CAMPAIGN_MANAGER__CM360_CAMPAIGN_CM360_MODEL,
            EnumDimensions.DOUBLECLICK_CAMPAIGN_MANAGER__CM360_CREATIVE_TYPE_ID_GA_MODEL,
            EnumDimensions.DOUBLECLICK_CAMPAIGN_MANAGER__CM360_CREATIVE_GA_MODEL,
            EnumDimensions.DOUBLECLICK_CAMPAIGN_MANAGER__CM360_ADVERTISER_ID,
            EnumDimensions.DOUBLECLICK_CAMPAIGN_MANAGER__CM360_SITE_CM360_MODEL,
            EnumDimensions.DOUBLECLICK_CAMPAIGN_MANAGER__CM360_PLACEMENT_ID_GA_MODEL,
            EnumDimensions.DOUBLECLICK_CAMPAIGN_MANAGER__CM360_ADVERTISER_GA_MODEL,
            EnumDimensions.DOUBLECLICK_CAMPAIGN_MANAGER__CM360_CREATIVE_TYPE_GA_MODEL,
            EnumDimensions.DOUBLECLICK_CAMPAIGN_MANAGER__CM360_CREATIVE_TYPE_ID_CM360_MODEL,
            EnumDimensions.DOUBLECLICK_CAMPAIGN_MANAGER__CM360_PLACEMENT_GA_MODEL,
            EnumDimensions.DOUBLECLICK_CAMPAIGN_MANAGER__CM360_ADVERTISER_ID_CM360_MODEL,
            EnumDimensions.DOUBLECLICK_CAMPAIGN_MANAGER__CM360_AD,
            EnumDimensions.DOUBLECLICK_CAMPAIGN_MANAGER__CM360_FLOODLIGHT_CONFIGURATION_ID_GA_MODEL,
            EnumDimensions.DOUBLECLICK_CAMPAIGN_MANAGER__CM360_SITE_ID_CM360_MODEL,
            EnumDimensions.DOUBLECLICK_CAMPAIGN_MANAGER__CM360_CREATIVE_TYPE_CM360_MODEL,
            EnumDimensions.DOUBLECLICK_CAMPAIGN_MANAGER__CM360_AD_ID_CM360_MODEL,
            EnumDimensions.DOUBLECLICK_CAMPAIGN_MANAGER__CM360_ACTIVITY_GROUP_ID,
            EnumDimensions.DOUBLECLICK_CAMPAIGN_MANAGER__CM360_CAMPAIGN_ID_GA_MODEL,
            EnumDimensions.DOUBLECLICK_CAMPAIGN_MANAGER__CM360_CAMPAIGN_GA_MODEL,
            EnumDimensions.DOUBLECLICK_CAMPAIGN_MANAGER__CM360_PLACEMENT_ID_CM360_MODEL
    ), Arrays.asList(
            EnumMetrics.DOUBLECLICK_CAMPAIGN_MANAGER__CM_COST,
            EnumMetrics.DOUBLECLICK_CAMPAIGN_MANAGER__CM_CONVERSIONS,
            EnumMetrics.DOUBLECLICK_CAMPAIGN_MANAGER__CM_REVENUE,
            EnumMetrics.DOUBLECLICK_CAMPAIGN_MANAGER__CM_ROAS,
            EnumMetrics.DOUBLECLICK_CAMPAIGN_MANAGER__CM_RPC,
            EnumMetrics.DOUBLECLICK_CAMPAIGN_MANAGER__CM_CTR,
            EnumMetrics.DOUBLECLICK_CAMPAIGN_MANAGER__CM_CLICKS,
            EnumMetrics.DOUBLECLICK_CAMPAIGN_MANAGER__CM_CPC,
            EnumMetrics.DOUBLECLICK_CAMPAIGN_MANAGER__CM_IMPRESSIONS
    )),
    DOUBLECLICK_FOR_PUBLISHERS(Arrays.asList(
            EnumDimensions.DOUBLECLICK_FOR_PUBLISHERS_BACKFILL__GAM_LINE_ITEM_NAME,
            EnumDimensions.DOUBLECLICK_FOR_PUBLISHERS_BACKFILL__GAM_LINE_ITEM_ID
    ), Arrays.asList(
            EnumMetrics.DOUBLECLICK_FOR_PUBLISHERS__GAM_COVERAGE,
            EnumMetrics.DOUBLECLICK_FOR_PUBLISHERS__GAM_IMPRESSIONS,
            EnumMetrics.DOUBLECLICK_FOR_PUBLISHERS_BACKFILL__GAM_BACKFILL_COVERAGE,
            EnumMetrics.DOUBLECLICK_FOR_PUBLISHERS__GAM_CTR,
            EnumMetrics.DOUBLECLICK_FOR_PUBLISHERS__GAM_IMPRESSIONS_PER_SESSION,
            EnumMetrics.DOUBLECLICK_FOR_PUBLISHERS__GAM_REVENUE_PER_1000_SESSIONS,
            EnumMetrics.DOUBLECLICK_FOR_PUBLISHERS__GAM_ECPM,
            EnumMetrics.DOUBLECLICK_FOR_PUBLISHERS__GAM_CLICKS,
            EnumMetrics.DOUBLECLICK_FOR_PUBLISHERS_BACKFILL__GAM_BACKFILL_CTR,
            EnumMetrics.DOUBLECLICK_FOR_PUBLISHERS_BACKFILL__GAM_BACKFILL_CLICKS,
            EnumMetrics.DOUBLECLICK_FOR_PUBLISHERS_BACKFILL__GAM_BACKFILL_IMPRESSIONS_PER_SESSION,
            EnumMetrics.DOUBLECLICK_FOR_PUBLISHERS__GAM_MONETIZED_PAGEVIEWS,
            EnumMetrics.DOUBLECLICK_FOR_PUBLISHERS_BACKFILL__GAM_BACKFILL_MONETIZED_PAGEVIEWS,
            EnumMetrics.DOUBLECLICK_FOR_PUBLISHERS_BACKFILL__GAM_BACKFILL_REVENUE,
            EnumMetrics.DOUBLECLICK_FOR_PUBLISHERS_BACKFILL__GAM_BACKFILL_REVENUE_PER_1000_SESSIONS,
            EnumMetrics.DOUBLECLICK_FOR_PUBLISHERS_BACKFILL__GAM_BACKFILL_ECPM,
            EnumMetrics.DOUBLECLICK_FOR_PUBLISHERS_BACKFILL__GAM_BACKFILL_IMPRESSIONS,
            EnumMetrics.DOUBLECLICK_FOR_PUBLISHERS__GAM_REVENUE,
            EnumMetrics.DOUBLECLICK_FOR_PUBLISHERS__GAM_VIEWABLE_IMPRESSIONS_PERCENT,
            EnumMetrics.DOUBLECLICK_FOR_PUBLISHERS_BACKFILL__GAM_BACKFILL_VIEWABLE_IMPRESSIONS_PERCENT
    )),
    DOUBLECLICK_FOR_PUBLISHERS_BACKFILL(Arrays.asList(
            EnumDimensions.DOUBLECLICK_FOR_PUBLISHERS_BACKFILL__GAM_LINE_ITEM_NAME,
            EnumDimensions.DOUBLECLICK_FOR_PUBLISHERS_BACKFILL__GAM_LINE_ITEM_ID
    ), Arrays.asList(
            EnumMetrics.DOUBLECLICK_FOR_PUBLISHERS_BACKFILL__GAM_BACKFILL_COVERAGE,
            EnumMetrics.DOUBLECLICK_FOR_PUBLISHERS_BACKFILL__GAM_BACKFILL_CTR,
            EnumMetrics.DOUBLECLICK_FOR_PUBLISHERS_BACKFILL__GAM_BACKFILL_CLICKS,
            EnumMetrics.DOUBLECLICK_FOR_PUBLISHERS_BACKFILL__GAM_BACKFILL_IMPRESSIONS_PER_SESSION,
            EnumMetrics.DOUBLECLICK_FOR_PUBLISHERS_BACKFILL__GAM_BACKFILL_MONETIZED_PAGEVIEWS,
            EnumMetrics.DOUBLECLICK_FOR_PUBLISHERS_BACKFILL__GAM_BACKFILL_REVENUE,
            EnumMetrics.DOUBLECLICK_FOR_PUBLISHERS_BACKFILL__GAM_BACKFILL_REVENUE_PER_1000_SESSIONS,
            EnumMetrics.DOUBLECLICK_FOR_PUBLISHERS_BACKFILL__GAM_BACKFILL_ECPM,
            EnumMetrics.DOUBLECLICK_FOR_PUBLISHERS_BACKFILL__GAM_BACKFILL_IMPRESSIONS,
            EnumMetrics.DOUBLECLICK_FOR_PUBLISHERS_BACKFILL__GAM_BACKFILL_VIEWABLE_IMPRESSIONS_PERCENT
    )),
    DOUBLECLICK_SEARCH(Arrays.asList(
            EnumDimensions.DOUBLECLICK_SEARCH__SA360_ENGINE_ACCOUNT_ID,
            EnumDimensions.DOUBLECLICK_SEARCH__SA360_AD_GROUP_ID,
            EnumDimensions.DOUBLECLICK_SEARCH__SA360_KEYWORD_ID,
            EnumDimensions.DOUBLECLICK_SEARCH__SA360_CAMPAIGN_ID,
            EnumDimensions.DOUBLECLICK_SEARCH__SA360_KEYWORD,
            EnumDimensions.DOUBLECLICK_SEARCH__SA360_CAMPAIGN,
            EnumDimensions.DOUBLECLICK_SEARCH__SA360_ADVERTISER,
            EnumDimensions.DOUBLECLICK_SEARCH__SA360_ADVERTISER_ID,
            EnumDimensions.DOUBLECLICK_SEARCH__SA360_AD_GROUP,
            EnumDimensions.DOUBLECLICK_SEARCH__SA360_AGENCY,
            EnumDimensions.DOUBLECLICK_SEARCH__SA360_AGENCY_ID,
            EnumDimensions.DOUBLECLICK_SEARCH__SA360_ENGINE_ACCOUNT
    ), Arrays.asList(
            EnumMetrics.DOUBLECLICK_SEARCH__SA360_CPC,
            EnumMetrics.DOUBLECLICK_SEARCH__SA360_COST,
            EnumMetrics.DOUBLECLICK_SEARCH__SA360_CLICKS,
            EnumMetrics.DOUBLECLICK_SEARCH__SA360_IMPRESSIONS,
            EnumMetrics.DOUBLECLICK_SEARCH__SA360_CTR,
            EnumMetrics.DOUBLECLICK_SEARCH__SA360_ROAS,
            EnumMetrics.DOUBLECLICK_SEARCH__SA360_PROFIT,
            EnumMetrics.DOUBLECLICK_SEARCH__SA360_RPC
    )),
    ECOMMERCE(Arrays.asList(
            EnumDimensions.ECOMMERCE__INTERNAL_PROMOTION_CREATIVE,
            EnumDimensions.ECOMMERCE__CHECKOUT_OPTIONS,
            EnumDimensions.ECOMMERCE__PRODUCT,
            EnumDimensions.ECOMMERCE__PRODUCT_SKU,
            EnumDimensions.ECOMMERCE__PRODUCT_LIST_NAME,
            EnumDimensions.ECOMMERCE__INTERNAL_PROMOTION_NAME,
            EnumDimensions.ECOMMERCE__INTERNAL_PROMOTION_POSITION,
            EnumDimensions.ECOMMERCE__PRODUCT_VARIANT,
            EnumDimensions.ECOMMERCE__PRODUCT_LIST_POSITION,
            EnumDimensions.ECOMMERCE__PRODUCT_COUPON_CODE,
            EnumDimensions.ECOMMERCE__DAYS_TO_TRANSACTION,
            EnumDimensions.ECOMMERCE__PRODUCT_CATEGORY,
            EnumDimensions.ECOMMERCE__SESSIONS_TO_TRANSACTION,
            EnumDimensions.ECOMMERCE__SHOPPING_STAGE,
            EnumDimensions.ECOMMERCE__CURRENCY_CODE,
            EnumDimensions.ECOMMERCE__INTERNAL_PROMOTION_ID,
            EnumDimensions.ECOMMERCE__PRODUCT_BRAND,
            EnumDimensions.ECOMMERCE__PRODUCT_CATEGORY_LEVEL_XX,
            EnumDimensions.ECOMMERCE__TRANSACTION_ID,
            EnumDimensions.ECOMMERCE__ORDER_COUPON_CODE,
            EnumDimensions.ECOMMERCE__PRODUCT_CATEGORY_ENHANCED_ECOMMERCE,
            EnumDimensions.ECOMMERCE__AFFILIATION
    ), Arrays.asList(
            EnumMetrics.ECOMMERCE__REFUNDS,
            EnumMetrics.ECOMMERCE__AVG_QTY,
            EnumMetrics.ECOMMERCE__PRODUCT_DETAIL_VIEWS,
            EnumMetrics.ECOMMERCE__QUANTITY_REFUNDED,
            EnumMetrics.ECOMMERCE__TAX,
            EnumMetrics.ECOMMERCE__TRANSACTIONS,
            EnumMetrics.ECOMMERCE__SHIPPING,
            EnumMetrics.ECOMMERCE__AVG_PRICE,
            EnumMetrics.ECOMMERCE__INTERNAL_PROMOTION_VIEWS,
            EnumMetrics.ECOMMERCE__TOTAL_VALUE,
            EnumMetrics.ECOMMERCE__CARTTODETAIL_RATE,
            EnumMetrics.ECOMMERCE__PRODUCT_REFUNDS,
            EnumMetrics.ECOMMERCE__QUANTITY_CHECKED_OUT,
            EnumMetrics.ECOMMERCE__LOCAL_TAX,
            EnumMetrics.ECOMMERCE__ECOMMERCE_CONVERSION_RATE,
            EnumMetrics.ECOMMERCE__INTERNAL_PROMOTION_CTR,
            EnumMetrics.ECOMMERCE__LOCAL_SHIPPING,
            EnumMetrics.ECOMMERCE__PER_SESSION_VALUE,
            EnumMetrics.ECOMMERCE__LOCAL_PRODUCT_REFUND_AMOUNT,
            EnumMetrics.ECOMMERCE__PRODUCT_ADDS_TO_CART,
            EnumMetrics.ECOMMERCE__PRODUCT_LIST_VIEWS,
            EnumMetrics.ECOMMERCE__TRANSACTIONS_PER_USER,
            EnumMetrics.ECOMMERCE__PRODUCT_REVENUE_PER_PURCHASE,
            EnumMetrics.ECOMMERCE__PRODUCT_REFUND_AMOUNT,
            EnumMetrics.ECOMMERCE__PRODUCT_CHECKOUTS,
            EnumMetrics.ECOMMERCE__PRODUCT_REVENUE,
            EnumMetrics.ECOMMERCE__UNIQUE_PURCHASES,
            EnumMetrics.ECOMMERCE__PRODUCT_LIST_CLICKS,
            EnumMetrics.ECOMMERCE__QUANTITY_ADDED_TO_CART,
            EnumMetrics.ECOMMERCE__REFUND_AMOUNT,
            EnumMetrics.ECOMMERCE__REVENUE,
            EnumMetrics.ECOMMERCE__LOCAL_PRODUCT_REVENUE,
            EnumMetrics.ECOMMERCE__QUANTITY,
            EnumMetrics.ECOMMERCE__PRODUCT_REMOVES_FROM_CART,
            EnumMetrics.ECOMMERCE__REVENUE_PER_USER,
            EnumMetrics.ECOMMERCE__QUANTITY_REMOVED_FROM_CART,
            EnumMetrics.ECOMMERCE__PRODUCT_LIST_CTR,
            EnumMetrics.ECOMMERCE__INTERNAL_PROMOTION_CLICKS,
            EnumMetrics.ECOMMERCE__BUYTODETAIL_RATE,
            EnumMetrics.ECOMMERCE__LOCAL_REFUND_AMOUNT,
            EnumMetrics.ECOMMERCE__AVG_ORDER_VALUE,
            EnumMetrics.ECOMMERCE__LOCAL_REVENUE
    )),
    EVENT_TRACKING(Arrays.asList(
            EnumDimensions.EVENT_TRACKING__EVENT_CATEGORY,
            EnumDimensions.EVENT_TRACKING__EVENT_ACTION,
            EnumDimensions.EVENT_TRACKING__EVENT_LABEL
    ), Arrays.asList(
            EnumMetrics.EVENT_TRACKING__SESSIONS_WITH_EVENT,
            EnumMetrics.EVENT_TRACKING__UNIQUE_EVENTS,
            EnumMetrics.EVENT_TRACKING__AVG_VALUE,
            EnumMetrics.EVENT_TRACKING__EVENT_VALUE,
            EnumMetrics.EVENT_TRACKING__TOTAL_EVENTS,
            EnumMetrics.EVENT_TRACKING__EVENTS_PER_SESSION_WITH_EVENT
    )),
    EXCEPTIONS(Arrays.asList(
            EnumDimensions.EXCEPTIONS__EXCEPTION_DESCRIPTION
    ), Arrays.asList(
            EnumMetrics.EXCEPTIONS__EXCEPTIONS,
            EnumMetrics.EXCEPTIONS__CRASHES,
            EnumMetrics.EXCEPTIONS__CRASHES_PER_SCREEN,
            EnumMetrics.EXCEPTIONS__EXCEPTIONS_PER_SCREEN
    )),
    GEO_NETWORK(Arrays.asList(
            EnumDimensions.GEO_NETWORK__SERVICE_PROVIDER,
            EnumDimensions.GEO_NETWORK__CITY,
            EnumDimensions.GEO_NETWORK__LATITUDE,
            EnumDimensions.GEO_NETWORK__LONGITUDE,
            EnumDimensions.GEO_NETWORK__CONTINENT_ID,
            EnumDimensions.GEO_NETWORK__REGION,
            EnumDimensions.GEO_NETWORK__COUNTRY_ISO_CODE,
            EnumDimensions.GEO_NETWORK__METRO,
            EnumDimensions.GEO_NETWORK__NETWORK_DOMAIN,
            EnumDimensions.GEO_NETWORK__REGION_ID,
            EnumDimensions.GEO_NETWORK__CITY_ID,
            EnumDimensions.GEO_NETWORK__CONTINENT,
            EnumDimensions.GEO_NETWORK__SUB_CONTINENT_CODE,
            EnumDimensions.GEO_NETWORK__SUB_CONTINENT,
            EnumDimensions.GEO_NETWORK__COUNTRY,
            EnumDimensions.GEO_NETWORK__REGION_ISO_CODE,
            EnumDimensions.GEO_NETWORK__METRO_ID
    ), Arrays.asList(
    )),
    GOAL_CONVERSIONS(Arrays.asList(
            EnumDimensions.GOAL_CONVERSIONS__GOAL_COMPLETION_LOCATION,
            EnumDimensions.GOAL_CONVERSIONS__GOAL_PREVIOUS_STEP_1,
            EnumDimensions.GOAL_CONVERSIONS__GOAL_PREVIOUS_STEP_3,
            EnumDimensions.GOAL_CONVERSIONS__GOAL_PREVIOUS_STEP_2
    ), Arrays.asList(
            EnumMetrics.GOAL_CONVERSIONS__GOAL_STARTS,
            EnumMetrics.GOAL_CONVERSIONS__GOAL_XX_VALUE,
            EnumMetrics.GOAL_CONVERSIONS__GOAL_XX_ABANDONED_FUNNELS,
            EnumMetrics.GOAL_CONVERSIONS__GOAL_XX_STARTS,
            EnumMetrics.GOAL_CONVERSIONS__GOAL_XX_COMPLETIONS,
            EnumMetrics.GOAL_CONVERSIONS__GOAL_XX_ABANDONMENT_RATE,
            EnumMetrics.GOAL_CONVERSIONS__PER_SESSION_GOAL_VALUE,
            EnumMetrics.GOAL_CONVERSIONS__GOAL_COMPLETIONS,
            EnumMetrics.GOAL_CONVERSIONS__GOAL_CONVERSION_RATE,
            EnumMetrics.GOAL_CONVERSIONS__ABANDONED_FUNNELS,
            EnumMetrics.GOAL_CONVERSIONS__GOAL_XX_CONVERSION_RATE,
            EnumMetrics.GOAL_CONVERSIONS__TOTAL_ABANDONMENT_RATE,
            EnumMetrics.GOAL_CONVERSIONS__GOAL_VALUE
    )),
    INTERNAL_SEARCH(Arrays.asList(
            EnumDimensions.INTERNAL_SEARCH__SITE_SEARCH_STATUS,
            EnumDimensions.INTERNAL_SEARCH__START_PAGE,
            EnumDimensions.INTERNAL_SEARCH__SEARCH_DESTINATION_PAGE,
            EnumDimensions.INTERNAL_SEARCH__SITE_SEARCH_CATEGORY,
            EnumDimensions.INTERNAL_SEARCH__DESTINATION_PAGE,
            EnumDimensions.INTERNAL_SEARCH__REFINED_KEYWORD,
            EnumDimensions.INTERNAL_SEARCH__SEARCH_TERM
    ), Arrays.asList(
            EnumMetrics.INTERNAL_SEARCH__PERCENT_SEARCH_EXITS,
            EnumMetrics.INTERNAL_SEARCH__RESULTS_PAGEVIEWS,
            EnumMetrics.INTERNAL_SEARCH__PERCENT_SESSIONS_WITH_SEARCH,
            EnumMetrics.INTERNAL_SEARCH__SITE_SEARCH_GOAL_XX_CONVERSION_RATE,
            EnumMetrics.INTERNAL_SEARCH__RESULTS_PAGEVIEWS_PER_SEARCH,
            EnumMetrics.INTERNAL_SEARCH__PER_SEARCH_GOAL_VALUE,
            EnumMetrics.INTERNAL_SEARCH__SEARCH_REFINEMENTS,
            EnumMetrics.INTERNAL_SEARCH__SITE_SEARCH_GOAL_CONVERSION_RATE,
            EnumMetrics.INTERNAL_SEARCH__PERCENT_SEARCH_REFINEMENTS,
            EnumMetrics.INTERNAL_SEARCH__SESSIONS_WITH_SEARCH,
            EnumMetrics.INTERNAL_SEARCH__TIME_AFTER_SEARCH,
            EnumMetrics.INTERNAL_SEARCH__TOTAL_UNIQUE_SEARCHES,
            EnumMetrics.INTERNAL_SEARCH__AVG_SEARCH_DEPTH,
            EnumMetrics.INTERNAL_SEARCH__SEARCH_EXITS,
            EnumMetrics.INTERNAL_SEARCH__SEARCH_DEPTH
    )),
    LIFETIME_VALUE_AND_COHORTS(Arrays.asList(
            EnumDimensions.LIFETIME_VALUE_AND_COHORTS__ACQUISITION_CHANNEL,
            EnumDimensions.LIFETIME_VALUE_AND_COHORTS__ACQUISITION_MEDIUM,
            EnumDimensions.LIFETIME_VALUE_AND_COHORTS__WEEK,
            EnumDimensions.LIFETIME_VALUE_AND_COHORTS__ACQUISITION_SOURCE,
            EnumDimensions.LIFETIME_VALUE_AND_COHORTS__ACQUISITION_SOURCE_PER_MEDIUM,
            EnumDimensions.LIFETIME_VALUE_AND_COHORTS__COHORT,
            EnumDimensions.LIFETIME_VALUE_AND_COHORTS__DAY,
            EnumDimensions.LIFETIME_VALUE_AND_COHORTS__ACQUISITION_CAMPAIGN,
            EnumDimensions.LIFETIME_VALUE_AND_COHORTS__MONTH
    ), Arrays.asList(
            EnumMetrics.LIFETIME_VALUE_AND_COHORTS__SESSION_DURATION_PER_USER,
            EnumMetrics.LIFETIME_VALUE_AND_COHORTS__USER_RETENTION,
            EnumMetrics.LIFETIME_VALUE_AND_COHORTS__APPVIEWS_PER_USER_LTV,
            EnumMetrics.LIFETIME_VALUE_AND_COHORTS__PAGEVIEWS_PER_USER,
            EnumMetrics.LIFETIME_VALUE_AND_COHORTS__REVENUE_PER_USER,
            EnumMetrics.LIFETIME_VALUE_AND_COHORTS__PAGEVIEWS_PER_USER_LTV,
            EnumMetrics.LIFETIME_VALUE_AND_COHORTS__SESSIONS_PER_USER_LTV,
            EnumMetrics.LIFETIME_VALUE_AND_COHORTS__SESSION_DURATION_PER_USER_LTV,
            EnumMetrics.LIFETIME_VALUE_AND_COHORTS__SESSIONS_PER_USER,
            EnumMetrics.LIFETIME_VALUE_AND_COHORTS__REVENUE_PER_USER_LTV,
            EnumMetrics.LIFETIME_VALUE_AND_COHORTS__TOTAL_USERS,
            EnumMetrics.LIFETIME_VALUE_AND_COHORTS__USERS,
            EnumMetrics.LIFETIME_VALUE_AND_COHORTS__GOAL_COMPLETIONS_PER_USER,
            EnumMetrics.LIFETIME_VALUE_AND_COHORTS__GOAL_COMPLETIONS_PER_USER_LTV,
            EnumMetrics.LIFETIME_VALUE_AND_COHORTS__APPVIEWS_PER_USER
    )),
    PAGE_TRACKING(Arrays.asList(
            EnumDimensions.PAGE_TRACKING__PAGE,
            EnumDimensions.PAGE_TRACKING__HOSTNAME,
            EnumDimensions.PAGE_TRACKING__PAGE_DEPTH,
            EnumDimensions.PAGE_TRACKING__PAGE_TITLE,
            EnumDimensions.PAGE_TRACKING__EXIT_PAGE,
            EnumDimensions.PAGE_TRACKING__PREVIOUS_PAGE_PATH,
            EnumDimensions.PAGE_TRACKING__LANDING_PAGE,
            EnumDimensions.PAGE_TRACKING__PAGE_PATH_LEVEL_1,
            EnumDimensions.PAGE_TRACKING__PAGE_PATH_LEVEL_2,
            EnumDimensions.PAGE_TRACKING__PAGE_PATH_LEVEL_3,
            EnumDimensions.PAGE_TRACKING__PAGE_PATH_LEVEL_4,
            EnumDimensions.PAGE_TRACKING__SECOND_PAGE
    ), Arrays.asList(
            EnumMetrics.PAGE_TRACKING__PERCENT_EXIT,
            EnumMetrics.PAGE_TRACKING__TIME_ON_PAGE,
            EnumMetrics.PAGE_TRACKING__PAGE_VALUE,
            EnumMetrics.PAGE_TRACKING__ENTRANCES,
            EnumMetrics.PAGE_TRACKING__UNIQUE_PAGEVIEWS,
            EnumMetrics.PAGE_TRACKING__ENTRANCES_PER_PAGEVIEWS,
            EnumMetrics.PAGE_TRACKING__EXITS,
            EnumMetrics.PAGE_TRACKING__PAGEVIEWS,
            EnumMetrics.PAGE_TRACKING__AVG_TIME_ON_PAGE,
            EnumMetrics.PAGE_TRACKING__PAGES_PER_SESSION
    )),
    PLATFORM_OR_DEVICE(Arrays.asList(
            EnumDimensions.PLATFORM_OR_DEVICE__BROWSER_VERSION,
            EnumDimensions.PLATFORM_OR_DEVICE__OPERATING_SYSTEM_VERSION,
            EnumDimensions.PLATFORM_OR_DEVICE__BROWSER_SIZE,
            EnumDimensions.PLATFORM_OR_DEVICE__MOBILE_INPUT_SELECTOR,
            EnumDimensions.PLATFORM_OR_DEVICE__DATA_SOURCE,
            EnumDimensions.PLATFORM_OR_DEVICE__OPERATING_SYSTEM,
            EnumDimensions.PLATFORM_OR_DEVICE__MOBILE_DEVICE_MODEL,
            EnumDimensions.PLATFORM_OR_DEVICE__MOBILE_DEVICE_MARKETING_NAME,
            EnumDimensions.PLATFORM_OR_DEVICE__BROWSER,
            EnumDimensions.PLATFORM_OR_DEVICE__MOBILE_DEVICE_INFO,
            EnumDimensions.PLATFORM_OR_DEVICE__DEVICE_CATEGORY,
            EnumDimensions.PLATFORM_OR_DEVICE__MOBILE_DEVICE_BRANDING
    ), Arrays.asList(
    )),
    PUBLISHER(Arrays.asList(
    ), Arrays.asList(
            EnumMetrics.PUBLISHER__PUBLISHER_CTR,
            EnumMetrics.PUBLISHER__PUBLISHER_REVENUE,
            EnumMetrics.PUBLISHER__PUBLISHER_VIEWABLE_IMPRESSIONS_PERCENT,
            EnumMetrics.PUBLISHER__PUBLISHER_IMPRESSIONS_PER_SESSION,
            EnumMetrics.PUBLISHER__PUBLISHER_CLICKS,
            EnumMetrics.PUBLISHER__PUBLISHER_COVERAGE,
            EnumMetrics.PUBLISHER__PUBLISHER_MONETIZED_PAGEVIEWS,
            EnumMetrics.PUBLISHER__PUBLISHER_REVENUE_PER_1000_SESSIONS,
            EnumMetrics.PUBLISHER__PUBLISHER_IMPRESSIONS,
            EnumMetrics.PUBLISHER__PUBLISHER_ECPM
    )),
    SESSION(Arrays.asList(
            EnumDimensions.SESSION__SESSION_DURATION
    ), Arrays.asList(
            EnumMetrics.SESSION__BOUNCE_RATE,
            EnumMetrics.SESSION__BOUNCES,
            EnumMetrics.SESSION__SESSION_DURATION,
            EnumMetrics.SESSION__SESSIONS,
            EnumMetrics.SESSION__AVG_SESSION_DURATION,
            EnumMetrics.SESSION__UNIQUE_DIMENSION_COMBINATIONS,
            EnumMetrics.SESSION__HITS
    )),
    SITE_SPEED(Arrays.asList(
    ), Arrays.asList(
            EnumMetrics.SITE_SPEED__AVG_REDIRECTION_TIME_SEC,
            EnumMetrics.SITE_SPEED__SERVER_CONNECTION_TIME_MS,
            EnumMetrics.SITE_SPEED__AVG_SERVER_RESPONSE_TIME_SEC,
            EnumMetrics.SITE_SPEED__PAGE_LOAD_SAMPLE,
            EnumMetrics.SITE_SPEED__PAGE_LOAD_TIME_MS,
            EnumMetrics.SITE_SPEED__AVG_PAGE_LOAD_TIME_SEC,
            EnumMetrics.SITE_SPEED__PAGE_DOWNLOAD_TIME_MS,
            EnumMetrics.SITE_SPEED__REDIRECTION_TIME_MS,
            EnumMetrics.SITE_SPEED__DOMAIN_LOOKUP_TIME_MS,
            EnumMetrics.SITE_SPEED__DOCUMENT_INTERACTIVE_TIME_MS,
            EnumMetrics.SITE_SPEED__DOCUMENT_CONTENT_LOADED_TIME_MS,
            EnumMetrics.SITE_SPEED__SERVER_RESPONSE_TIME_MS,
            EnumMetrics.SITE_SPEED__AVG_DOMAIN_LOOKUP_TIME_SEC,
            EnumMetrics.SITE_SPEED__AVG_DOCUMENT_CONTENT_LOADED_TIME_SEC,
            EnumMetrics.SITE_SPEED__AVG_DOCUMENT_INTERACTIVE_TIME_SEC,
            EnumMetrics.SITE_SPEED__DOM_LATENCY_METRICS_SAMPLE,
            EnumMetrics.SITE_SPEED__AVG_SERVER_CONNECTION_TIME_SEC,
            EnumMetrics.SITE_SPEED__SPEED_METRICS_SAMPLE,
            EnumMetrics.SITE_SPEED__AVG_PAGE_DOWNLOAD_TIME_SEC
    )),
    SOCIAL_INTERACTIONS(Arrays.asList(
            EnumDimensions.SOCIAL_INTERACTIONS__SOCIAL_TYPE,
            EnumDimensions.SOCIAL_INTERACTIONS__SOCIAL_ACTION,
            EnumDimensions.SOCIAL_INTERACTIONS__SOCIAL_NETWORK_AND_ACTION_HIT,
            EnumDimensions.SOCIAL_INTERACTIONS__SOCIAL_NETWORK,
            EnumDimensions.SOCIAL_INTERACTIONS__SOCIAL_ENTITY
    ), Arrays.asList(
            EnumMetrics.SOCIAL_INTERACTIONS__UNIQUE_SOCIAL_ACTIONS,
            EnumMetrics.SOCIAL_INTERACTIONS__ACTIONS_PER_SOCIAL_SESSION,
            EnumMetrics.SOCIAL_INTERACTIONS__SOCIAL_ACTIONS
    )),
    SYSTEM(Arrays.asList(
            EnumDimensions.SYSTEM__FLASH_VERSION,
            EnumDimensions.SYSTEM__JAVA_SUPPORT,
            EnumDimensions.SYSTEM__LANGUAGE,
            EnumDimensions.SYSTEM__SCREEN_COLORS,
            EnumDimensions.SYSTEM__SOURCE_PROPERTY_TRACKING_ID,
            EnumDimensions.SYSTEM__SCREEN_RESOLUTION,
            EnumDimensions.SYSTEM__SOURCE_PROPERTY_DISPLAY_NAME
    ), Arrays.asList(
    )),
    TIME(Arrays.asList(
            EnumDimensions.TIME__HOUR_INDEX,
            EnumDimensions.TIME__MONTH_OF_THE_YEAR,
            EnumDimensions.TIME__DAY_INDEX,
            EnumDimensions.TIME__MINUTE,
            EnumDimensions.TIME__MONTH_INDEX,
            EnumDimensions.TIME__MINUTE_INDEX,
            EnumDimensions.TIME__ISO_YEAR,
            EnumDimensions.TIME__DAY_OF_THE_MONTH,
            EnumDimensions.TIME__WEEK_INDEX,
            EnumDimensions.TIME__WEEK_OF_YEAR,
            EnumDimensions.TIME__YEAR,
            EnumDimensions.TIME__HOUR,
            EnumDimensions.TIME__MONTH_OF_YEAR,
            EnumDimensions.TIME__DATE_HOUR_AND_MINUTE,
            EnumDimensions.TIME__DAY_OF_WEEK,
            EnumDimensions.TIME__DATE,
            EnumDimensions.TIME__ISO_WEEK_OF_ISO_YEAR,
            EnumDimensions.TIME__HOUR_OF_DAY,
            EnumDimensions.TIME__WEEK_OF_THE_YEAR,
            EnumDimensions.TIME__DAY_OF_WEEK_NAME,
            EnumDimensions.TIME__ISO_WEEK_OF_THE_YEAR
    ), Arrays.asList(
    )),
    TRAFFIC_SOURCES(Arrays.asList(
            EnumDimensions.TRAFFIC_SOURCES__SOCIAL_NETWORK,
            EnumDimensions.TRAFFIC_SOURCES__AD_CONTENT,
            EnumDimensions.TRAFFIC_SOURCES__FULL_REFERRER,
            EnumDimensions.TRAFFIC_SOURCES__KEYWORD,
            EnumDimensions.TRAFFIC_SOURCES__CAMPAIGN,
            EnumDimensions.TRAFFIC_SOURCES__SOURCE,
            EnumDimensions.TRAFFIC_SOURCES__SOCIAL_SOURCE_REFERRAL,
            EnumDimensions.TRAFFIC_SOURCES__CAMPAIGN_CODE,
            EnumDimensions.TRAFFIC_SOURCES__MEDIUM,
            EnumDimensions.TRAFFIC_SOURCES__SOURCE_PER_MEDIUM,
            EnumDimensions.TRAFFIC_SOURCES__REFERRAL_PATH
    ), Arrays.asList(
            EnumMetrics.TRAFFIC_SOURCES__ORGANIC_SEARCHES
    )),
    USER(Arrays.asList(
            EnumDimensions.USER__USER_DEFINED_VALUE,
            EnumDimensions.USER_TIMINGS__TIMING_VARIABLE,
            EnumDimensions.USER_TIMINGS__TIMING_CATEGORY,
            EnumDimensions.USER__COUNT_OF_SESSIONS,
            EnumDimensions.USER__DAYS_SINCE_LAST_SESSION,
            EnumDimensions.USER__USER_BUCKET,
            EnumDimensions.USER__USER_TYPE,
            EnumDimensions.USER_TIMINGS__TIMING_LABEL
    ), Arrays.asList(
            EnumMetrics.USER__NUMBER_OF_SESSIONS_PER_USER,
            EnumMetrics.USER__14_DAY_ACTIVE_USERS,
            EnumMetrics.USER__28_DAY_ACTIVE_USERS,
            EnumMetrics.USER__30_DAY_ACTIVE_USERS,
            EnumMetrics.USER__PERCENT_NEW_SESSIONS,
            EnumMetrics.USER__NEW_USERS,
            EnumMetrics.USER__7_DAY_ACTIVE_USERS,
            EnumMetrics.USER_TIMINGS__AVG_USER_TIMING_SEC,
            EnumMetrics.USER__USERS,
            EnumMetrics.USER__1_DAY_ACTIVE_USERS,
            EnumMetrics.USER_TIMINGS__USER_TIMING_MS,
            EnumMetrics.USER_TIMINGS__USER_TIMING_SAMPLE
    )),
    USER_TIMINGS(Arrays.asList(
            EnumDimensions.USER_TIMINGS__TIMING_VARIABLE,
            EnumDimensions.USER_TIMINGS__TIMING_CATEGORY,
            EnumDimensions.USER_TIMINGS__TIMING_LABEL
    ), Arrays.asList(
            EnumMetrics.USER_TIMINGS__AVG_USER_TIMING_SEC,
            EnumMetrics.USER_TIMINGS__USER_TIMING_MS,
            EnumMetrics.USER_TIMINGS__USER_TIMING_SAMPLE
    ));

    private final List<EnumDimensions> dimensions;
    private final List<EnumMetrics> metrics;

    EnumGroup(final List<EnumDimensions> dimensions, List<EnumMetrics> metrics) {
        this.dimensions = dimensions;
        this.metrics = metrics;
    }

    public List<EnumDimensions> getDimensions() {
        return dimensions;
    }

    public List<EnumMetrics> getMetrics() {
        return metrics;
    }
}
